# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['src/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/frontend', 'frontend'),
        ('src/backend', 'backend'),
    ],
    hiddenimports=[
        'frontend',
        'frontend.main_window',
        'backend',
        'backend.controllers',
        'backend.controllers.controller',
        'backend.image_processing',
        'backend.motor_control',
        'backend.data',
        'backend.halcon',
        'backend.modules',
        'PySide6.QtCore',
        'PySide6.QtWidgets',
        'PySide6.QtGui',
        'cv2',
        'numpy',
        'pandas',
        'matplotlib',
        'scipy',
        'pillow',
        'mvtec_halcon',
        'SPiiPlusPython',
        'spinnaker_python',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        'tkinter',
        'IPython',
        'jedi',
        'parso',
        'jupyter',
        'nbformat',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PBA-Vision-0.X-amd64',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)