#/ Controller version = 3.13.01
#/ Date = 10/27/2025 10:57 AM
#/ User remarks = 
#0
!PNAME=
!PDESC=
!Gantry X Homing
ERRORUNMAP 0,0
DISABLE AX_X_COG, AX_X_YAW
S_SETUP.#SINCOSRP=1
MFLAGS(AX_X_COG).#HOME = 0
MFLAGS(AX_X_YAW).#HOME = 0
CALL DISABLE_SAFETY_MASKS
CALL INPUTSHAPING_OFF
CALL NONGANTRY_PARAMTERS
CALL X_IND_HOMING
WAIT 500

REAL MIDEAN, YAW
MIDEAN 	= (FPOS(AX_X_COG)+FPOS(AX_X_YAW))/2
YAW 	= (FPOS(AX_X_YAW)-FPOS(AX_X_COG));
SET FPOS(AX_X_COG) = MIDEAN
SET FPOS(AX_X_YAW) = YAW
CALL GANTRY_PARAMETERS
SET FPOS(AX_X_COG) = 0
SET FPOS(AX_X_YAW) = FPOS(AX_X_YAW)-YAW
CALL GANTRY_SETTINGS 
CALL INPUTSHAPING_ON
CALL RESTORE_SAFETY_PARA
MFLAGS(AX_X_COG).#HOME 	= 1
MFLAGS(AX_X_YAW).#HOME	= 1
TILL FVEL(AX_X_COG)<0.05
TILL ^PST(3).#RUN,20000
ENABLE AX_X_COG
STOP

!################## SUB ROUNTINES ##################
DISABLE_SAFETY_MASKS:
	DISP "DISABLE X SAFETY MASKS"
	FMASK(AX_X_COG).#SRL = 0;	FMASK(AX_X_YAW).#SRL = 0;
	FMASK(AX_X_COG).#SLL = 0;	FMASK(AX_X_YAW).#SLL = 0;
RET

RESTORE_SAFETY_PARA:
	DISP "RESTORE X SAFETY PARAMETERS"
	SRLIMIT(AX_X_COG)		= 395 ;	SRLIMIT(AX_X_YAW)		= 5 ;
	SLLIMIT(AX_X_COG)		= -25 ;	SLLIMIT(AX_X_YAW)		= -5 ;
	
	FMASK(AX_X_COG).#SRL 	= 1 ;	FMASK(AX_X_YAW).#SRL 	= 1 ;
	FMASK(AX_X_COG).#SLL 	= 1 ;	FMASK(AX_X_YAW).#SLL 	= 1 ;
	FMASK(AX_X_COG).#RL		= 1 ;	FMASK(AX_X_YAW).#RL		= 1 ;
	FMASK(AX_X_COG).#LL		= 1 ;	FMASK(AX_X_YAW).#LL		= 1 ;
	FMASK(AX_X_COG).#HOT	= 1 ;	FMASK(AX_X_YAW).#HOT	= 1 ;
	FMASK(AX_X_COG).#ENCNC	= 0 ;	FMASK(AX_X_YAW).#ENCNC	= 0 ;
	FMASK(AX_X_COG).#ENC2NC	= 0 ;	FMASK(AX_X_YAW).#ENC2NC	= 0 ;
	FMASK(AX_X_COG).#DRIVE	= 1 ;	FMASK(AX_X_YAW).#DRIVE	= 1 ;
	FMASK(AX_X_COG).#PE		= 0 ;	FMASK(AX_X_YAW).#PE		= 0 ;
	FMASK(AX_X_COG).#VL		= 1 ;	FMASK(AX_X_YAW).#VL		= 1 ;
	FMASK(AX_X_COG).#STO	= 1 ;	FMASK(AX_X_YAW).#STO	= 1 ;
RET

INPUTSHAPING_OFF:
	DISP "X INPUTSHAPING OFF"
	InShapeOFF AX_X_COG
RET

INPUTSHAPING_ON:
	DISP "X INPUTSHAPING ON"
	REAL InShapeTime(3);
	REAL InShapeSamples(3);
	InShapeTime(0)			= CTIME*00; 	InShapeSamples(0)		= 53909/1e5;
	InShapeTime(1)			= CTIME*45; 	InShapeSamples(1)		= 25179/1e5;
	InShapeTime(2)			= CTIME*46; 	InShapeSamples(2)		= 20912/1e5;
	InShapeOn AX_X_COG, InShapeTime, InShapeSamples
	WAIT 100
RET



GANTRY_SETTINGS:
	DISP "APPLY X GANTRY SETTINGS"
	FMASK(AX_X_COG).#RL		= 1 ;	FMASK(AX_X_YAW).#RL		= 0 ;
	FMASK(AX_X_COG).#LL		= 1 ;	FMASK(AX_X_YAW).#LL		= 0 ;
	FDEF(AX_X_COG).#RL 		= 1
	FDEF(AX_X_COG).#LL 		= 1
	FDEF(AX_X_COG).#SRL 	= 1
	FDEF(AX_X_COG).#SLL 	= 1
	
	VEL(AX_X_COG) 		= 1000
	ACC(AX_X_COG) 		= 6000
	DEC(AX_X_COG) 		= 6000
	JERK(AX_X_COG) 		= 180000
	KDEC(AX_X_COG)		= 12000
RET

NONGANTRY_PARAMTERS:
	DISP "APPLY X NON GANTRY PARAMETERS"
	FMASK(AX_X_COG).#RL = 1;	FMASK(AX_X_YAW).#RL = 1;
	FMASK(AX_X_COG).#LL = 1;	FMASK(AX_X_YAW).#LL = 1;
	FDEF(AX_X_COG).#RL 	= 0;	FDEF(AX_X_YAW).#RL 	= 0;
	FDEF(AX_X_COG).#LL 	= 0;	FDEF(AX_X_YAW).#LL 	= 0;
	
	DISP "SERVOBOOST DISABLED"
	SLSBORD(AX_X_COG) 	= 0;	SLSBORD(AX_X_YAW) 	= 0;

	ACC (AX_X_COG) 		= 1000;	ACC (AX_X_YAW) 		= 1000;
	DEC (AX_X_COG) 		= 1000;	DEC (AX_X_YAW) 		= 1000;
	KDEC(AX_X_COG) 		= 1000;	KDEC(AX_X_YAW) 		= 1000;
	JERK (AX_X_COG) 	= 5000;	JERK (AX_X_YAW) 	= 5000;
		
!X1 X2
	MFLAGS(AX_X_COG).#GANTRY 	= 0 ;	MFLAGS(AX_X_YAW).#GANTRY	= 0 ;
	SLPKP(AX_X_COG) 			= 50 ;	SLPKP(AX_X_YAW) 			= 50 ;
	SLVKP(AX_X_COG) 			= 300 ;	SLVKP(AX_X_YAW) 			= 300 ;
	SLVKI(AX_X_COG) 			= 50 ;	SLVKI(AX_X_YAW) 			= 50 ;
	SLVSOF(AX_X_COG) 			= 200 ;	SLVSOF(AX_X_YAW)			= 200 ;
	SLVSOFD(AX_X_COG) 			= 0.8 ;	SLVSOFD(AX_X_YAW) 			= 0.8 ;
	SLVKPIF(AX_X_COG)			= 1.2
	SLJFF(AX_X_COG)				= 0.25
	
	MFLAGS(AX_X_COG).#NOTCH 	= 0	;	MFLAGS(AX_X_YAW).#NOTCH 	= 0 ;
	MFLAGS(AX_X_COG).#BI_QUAD	= 0 ;	MFLAGS(AX_X_YAW).#BI_QUAD	= 0 ;
	MFLAGS(AX_X_COG).#BI_QUAD1	= 0 ;	MFLAGS(AX_X_YAW).#BI_QUAD1	= 0 ;

	XCURV(AX_X_COG) 			= 25 ;	XCURV(AX_X_YAW) 			= 25 ;
	XCURI(AX_X_COG) 			= 10 ;	XCURI(AX_X_YAW) 			= 15 ;
	SLAFF(AX_X_COG)				= 100;	SLAFF(AX_X_YAW) 			= 100;

	Gantry_Mode = 0
WAIT 100
RET

GANTRY_PARAMETERS:
	DISP "APPLY X GANTRY PARAMETERS"
	DISABLE (AX_X_COG, AX_X_YAW)
	MFLAGS(AX_X_COG).#GANTRY 	= 1;	MFLAGS(AX_X_YAW).#GANTRY	= 1;
	
	DISP "APPLY X COG SERVOBOOST"
	! ServoBoost
	SLSBORD(AX_X_COG)= 1;	SLSBORD(AX_X_YAW)= 0;		!ServoBoost Enable
	SLSBBW(AX_X_COG) = 70;	SLSBBW(AX_X_YAW) = 30;
	SLSBF(AX_X_COG)	 = 700;	SLSBF(AX_X_YAW)  = 200;
	
	! Current Saturation	
	XCURV(AX_X_COG)	= 100;	XCURV(AX_X_YAW) = 30;
	XCURI(AX_X_COG)	= 70;	XCURI(AX_X_YAW) = 15;
			 
	! Loops Gains
	SLIKP(AX_X_COG) = 1000;	SLIKP(AX_X_YAW) = 1000;		!Current Loop proportional
	SLIKI(AX_X_COG) = 200; SLIKI(AX_X_COG) = 200;		!Current Loop Integral
	SLPKP(AX_X_COG)	= 65;	SLPKP(AX_X_YAW) = 70;		!Position Loop proportional
	SLVKP(AX_X_COG)	= 350;	SLVKP(AX_X_YAW) = 250;		!Velocity Loop Proportional
	SLVKI(AX_X_COG)	= 250;	SLVKI(AX_X_YAW) = 200;		!Velocity loop Integral
		
	! Velocity Low Pass Filter
	MFLAGS(AX_X_COG).#NOFILT= 0;MFLAGS(AX_X_YAW).#NOFILT= 0;	
	SLVSOF(AX_X_COG)= 220;		SLVSOF(AX_X_YAW)= 50;	! Filter Bandwidth
	SLVSOFD(AX_X_COG)= 0.5;		SLVSOFD(AX_X_YAW)= 0.8;	! Filter Damping
		
	! Velocity Notch Filter 
	MFLAGS(AX_X_COG).#NOTCH=1;	MFLAGS(AX_X_YAW).#NOTCH= 1;
	SLVNATT(AX_X_COG)= 2;		SLVNATT(AX_X_YAW)= 3;  	! Notch Attenuation
	SLVNFRQ(AX_X_COG)= 200;		SLVNFRQ(AX_X_YAW)= 110; ! Notch Frequency
	SLVNWID(AX_X_COG)= 4;		SLVNWID(AX_X_YAW)= 15;  ! Notch Width
		
	! Velocity BiQuad Filter
	MFLAGS(AX_X_COG).#BI_QUAD= 0;  MFLAGS(AX_X_YAW).#BI_QUAD= 0; 
	SLVB0DD(AX_X_COG)= 0.1;		SLVB0DD(AX_X_YAW)= 0.8;  ! Denominator Damping
	SLVB0DF(AX_X_COG)= 950;		SLVB0DF(AX_X_YAW)= 180;  ! Denominator Frequency
	SLVB0ND(AX_X_COG)= 0.05;	SLVB0ND(AX_X_YAW)= 0.3;  ! Numerator Damping						
	SLVB0NF(AX_X_COG)= 950;		SLVB0NF(AX_X_YAW)= 300;  ! Numerator Frequency
		
	! Velocity BiQuad Filter 1 
	MFLAGS(AX_X_COG).#BI_QUAD1= 0;  MFLAGS(AX_X_YAW).#BI_QUAD1= 0;
	SLVB1DD(AX_X_COG)= 0.4;		SLVB1DD(AX_X_YAW)= 0.4; ! Denominator Damping						
	SLVB1DF(AX_X_COG)= 60;		SLVB1DF(AX_X_YAW)= 60; 	! Denominator Frequency
	SLVB1ND(AX_X_COG)= 0.6;		SLVB1ND(AX_X_YAW)= 0.6; ! Numerator Damping						
	SLVB1NF(AX_X_COG)= 60;		SLVB1NF(AX_X_YAW)= 60; 	! Numerator Frequency
		
	! FeedForward
	SLAFF(AX_X_COG)= 240;		SLAFF(AX_X_YAW)= 100;
	
	DISP "OPEN YAW"				
	MFLAGS(AX_X_YAW).#OPEN	= 1				
	Gantry_Mode = 1
RET

X_IND_HOMING:
	DISP "X0 X2 HOMING"
	MFLAGS(AX_X_COG).#OPEN = 0
	MFLAGS(AX_X_YAW).#OPEN = 0
	
	ENABLE (AX_X_COG, AX_X_YAW)
	JOG/v (AX_X_COG, AX_X_YAW), -50
	TILL (FAULT(AX_X_COG).#LL) & (FAULT(AX_X_YAW).#LL)
	HALT (AX_X_COG, AX_X_YAW)		
	IST(AX_X_COG).#IND=0 
	IST(AX_X_YAW).#IND=0 
	JOG/v (AX_X_COG,AX_X_YAW),20
	WAIT 100
	DISP "JOGGING TO INDEX"
	TILL IST(AX_X_COG).#IND & IST(AX_X_YAW).#IND 		
	HALT (AX_X_COG, AX_X_YAW)
	TILL ^AST(AX_X_COG).#MOVE & ^AST(AX_X_YAW).#MOVE
	WAIT 100
	SET FPOS(AX_X_COG)=FPOS(AX_X_COG)-IND(AX_X_COG)
	SET FPOS(AX_X_YAW)=FPOS(AX_X_YAW)-IND(AX_X_YAW)
	ENABLE (AX_X_COG, AX_X_YAW)
	DISP "X COG AND YAW ENABLED"
RET
#1
!PNAME=
!PDESC=
DISP "BUFFER 1 Gantry Y homing"
INT SEARCH_VEL
INT HOME_VEL
SEARCH_VEL			=20
HOME_VEL			=50
DISABLE AX_Y
ERRORUNMAP 1,0

MFLAGS(AX_Y).#HOME 	= 0	
CALL SOFT_LIMIT
CALL RESTORE_TUNING_PARA
CALL INPUTSHAPING_OFF
CALL LOAD_HOMING_PARA
CALL LIMIT_CURRENT
CALL HOME_Y !**************
CALL RESTORE_TUNING_PARA						
CALL RESTORE_SAFETY_MASKS
CALL RESTORE_MOTION_PARA
CALL INPUTSHAPING_ON
MFLAGS(AX_Y).#HOME = 1

DISP "BUFFER 1 STOPPED"
STOP

!###################### SUB ROUTINES ################
HOME_Y:
	DISP "Y HOMING"
	ENABLE AX_Y
	JOG/v AX_Y, -HOME_VEL
	TILL FAULT(AX_Y).#LL= 1
	KILL AX_Y
	TILL ^AST(AX_Y).#MOVE
	WAIT 100
	IST(AX_Y).#IND=0 
	JOG/v AX_Y,SEARCH_VEL
	DISP "JOGGING TO Y INDEX"
	WAIT 100
	TILL IST(AX_Y).#IND 
	KILL AX_Y
	TILL ^AST(AX_Y).#MOVE
	WAIT 100
	SET FPOS(AX_Y)=FPOS(AX_Y)-IND(AX_Y)
	CALL RESTORE_CURRENT
	PTP/ve AX_Y,0,100
RET

SOFT_LIMIT:
	DISP "Y SOFT LIITS APPLIED"
	FMASK(AX_Y).#SRL 	= 0
	FMASK(AX_Y).#SLL 	= 0
	SRLIMIT(AX_Y)		= 305
	SLLIMIT(AX_Y)		=-16
 
RET
LIMIT_CURRENT:
	XCURV(AX_Y) 		= 15
	XCURI(AX_Y) 		= 5
RET
RESTORE_CURRENT:
	XCURV(AX_Y) 		= 100
	XCURI(AX_Y) 		= 50
RET
LOAD_HOMING_PARA:
	DISP "Y HOMING PARAMETERS LOADED"
	FMASK(AX_Y).#RL 	= 1
	FMASK(AX_Y).#LL 	= 1
	FDEF(AX_Y).#RL 		= 0
	FDEF(AX_Y).#LL 		= 0
	SLSBORD(AX_Y) 		= 0
 
	ACC (AX_Y) 			= 1000
	DEC (AX_Y) 			= 1000
	KDEC(AX_Y) 			= 1000
	JERK (AX_Y) 		= 1000
RET
INPUTSHAPING_ON:
	DISP "Y INPUTSHAPING ON"
	REAL CnvTY(5), CnvAY(5)
	CnvTY(0)	= 0*0.5;      	CnvAY(0)	= 24813/1e5
	CnvTY(1)	= 17*0.5;     	CnvAY(1)	= 8441/1e5
	CnvTY(2)	= 22*0.5;     	CnvAY(2)	= 1639/1e5
	CnvTY(3)	= 27*0.5;    	CnvAY(3)	= 42464/1e5
	CnvTY(4)	= 51*0.5;    	CnvAY(4)	= 22643/1e5  
!-------------------------------------------------------------
InShapeOn AX_Y, CnvTY, CnvAY
WAIT 100
RET

INPUTSHAPING_OFF:
	DISP "Y INPUTSHAPING OFF"
	InShapeOFF AX_Y
RET

RESTORE_TUNING_PARA:
	DISP "Y TUNING PARAMETERS RESTORED"
	SLIKP(AX_Y)				= 1500
	SLIKI(AX_Y)				= 150
	SLPKP(AX_Y)				= 150
	SLPKI(AX_Y)				= 100
	SLVKP(AX_Y)				= 150
	SLVKPIF(AX_Y)			= 1
	SLVKI(AX_Y)				= 100
	SLVSOF(AX_Y)			= 300
	SLAFF(AX_Y)				= 320
	SLVSOFD(AX_Y) 			= 0.9
	SLJFF(AX_Y) 			= 0.3
	MFLAGS(AX_Y).#NOFILT 	= 0

	!Velocity notch filter
	MFLAGS(AX_Y).#NOTCH		= 1
	SLVNATT(AX_Y)			= 3
	SLVNFRQ(AX_Y)			= 512
	SLVNWID(AX_Y)			= 28

	!Velocity BQF 1 
	MFLAGS(AX_Y).#BI_QUAD	= 0
	SLVB0DD(AX_Y)			= 0.4
	SLVB0DF(AX_Y)			= 1495
	SLVB0ND(AX_Y)			= 0.057
	SLVB0NF(AX_Y)			= 1495

	!Velocity BQF 2
	MFLAGS(AX_Y).#BI_QUAD1		= 0
	SLVB1DD(AX_Y)			= 0.0865
	SLVB1DF(AX_Y)			= 516
	SLVB1ND(AX_Y)			= 0.0294
	SLVB1NF(AX_Y)			= 516
	
	!Current limit restoration 
	XCURV(AX_Y)				= 100
	XCURI(AX_Y)				= 50

	!SERVOBOOST 
	DISP "Y SERVOBOOST APLLIED"
	SLSBORD(AX_Y)			= 1
	SLSBBW(AX_Y)			= 30
	SLSBF(AX_Y)				= 900
	!INPOS CRITERION	
	TARGRAD(AX_Y)			= 0.0005
	SETTLE(AX_Y)			= 5
RET
RESTORE_MOTION_PARA:
	SLSBORD(AX_Y) 			= 1
	VEL (AX_Y) 				= 1000
	ACC (AX_Y) 				= 6000
	DEC (AX_Y) 				= 6000
	KDEC(AX_Y) 				= 10000
	JERK (AX_Y) 			= 190000
RET
RESTORE_SAFETY_MASKS:
	FDEF(AX_Y).#RL 			= 1
	FDEF(AX_Y).#LL 			= 1
	FDEF(AX_Y).#SRL 			= 1
	FDEF(AX_Y).#SLL 			= 1					  					  
	FMASK(AX_Y).#RL			= 1
	FMASK(AX_Y).#LL			= 1
	FMASK(AX_Y).#HOT			= 1
	FMASK(AX_Y).#SRL			= 1
	FMASK(AX_Y).#SLL			= 1
	FMASK(AX_Y).#ENCNC		= 0
	FMASK(AX_Y).#ENC2NC		= 0
	FMASK(AX_Y).#DRIVE		= 1
	FMASK(AX_Y).#PE			= 0
	FMASK(AX_Y).#VL			= 1
	FMASK(AX_Y).#STO			= 1
RET
STOP 
#3
!PNAME=
!PDESC=
DISP "BUFFER 3 Gantry Z Homing"
INT ZECOffset_ControlWord
INT ZECOffset_TouchProbeFunction
INT ZECOffset_ActualPosition
INT Slave_Number 			= 1
ZECOffset_ControlWord 		= ECGETOFFSET ("Controlword" , Slave_Number)
ZECOffset_ActualPosition 	= ECGETOFFSET ("Position Actual Value" , Slave_Number)
DISABLE AX_Z
MFLAGS(AX_Z).#HOME = 0

FMASK(AX_Z).#RL	= 1
FMASK(AX_Z).#LL	= 1
FDEF(AX_Z).#RL	= 0
FDEF(AX_Z).#LL	= 0

DISP "Z SOFT LIMITS DISABLE"
FMASK(AX_Z).#SRL 	= 0
FMASK(AX_Z).#SLL 	= 0
SRLIMIT(AX_Z)		= 32
SLLIMIT(AX_Z)		= -2					
ACC (AX_Z)		= 2000
DEC (AX_Z)		= 2000
KDEC(AX_Z)		= 3000
JERK (AX_Z)		= 10000

!Control Word Unmap
ECUNMAPIN(ZECOffset_ControlWord)
ECUNMAPOUT(ZECOffset_ControlWord)

DISP "Z Fault Clear Loop"
LOOP 2
	ECOUT(ZECOffset_ControlWord,ControlWord_Z)
	ControlWord_Z = 0x8F
	WAIT 150
	ControlWord_Z = 0x0F
	WAIT 150
	ECUNMAPIN(ZECOffset_ControlWord)
	ECUNMAPOUT(ZECOffset_ControlWord)
	WAIT 100
END
DISP "Z JOGGING TO RIGHT LIMIT"
ENABLE AX_Z
JOG/v AX_Z, 10
TILL FAULT(AX_Z).#RL = 1
HALT AX_Z
WAIT 100

DISP "Z Initiating touch probe"
INT Touch_Probe_Status = 0
REAL Index_Position
WHILE ^(Touch_Probe_Status = 1)
	COEWRITE/2 (Slave_Number,0x60B8,0,0x0)
	WAIT 100
	COEWRITE/2 (Slave_Number,0x60B8,0,0x15)
	WAIT 100
	Touch_Probe_Status = COEREAD/2(Slave_Number, 0x60B9, 0)
END
!**********************************************************
PTP/rv AX_Z,-20,10
DISP "Z Looking for index"
JOG/v AX_Z,-1
WAIT 200
WHILE ^(Touch_Probe_Status=67)
	Touch_Probe_Status=COEREAD/2 (Slave_Number,0x60B9,0)
	IF (Touch_Probe_Status = 67 )
		KILL AX_Z
		WAIT 300
	END
END
!!************************************************
ECIN (ZECOffset_ActualPosition, ActualPos_Z)
SET FPOS(AX_Z)=ActualPos_Z/1000
Index_Position=(COEREAD/4 (Slave_Number,0x60BA,0))/1000
SET FPOS(AX_Z)=(FPOS(AX_Z)-Index_Position)
WAIT 100

FMASK(AX_Z).#RL 	= 1
FMASK(AX_Z).#LL 	= 1
FDEF(AX_Z).#RL 		= 1
FDEF(AX_Z).#LL 		= 1
FDEF(AX_Z).#PE		= 0
FMASK(AX_Z).#PE		= 0
ERRA(AX_Z)			= 2
ERRI(AX_Z)			= 2
PTP/rv AX_Z,-10,10
TILL ^MST(AX_Z).#MOVE
WAIT 250
SET FPOS(AX_Z) = 0

VEL (AX_Z) 	= 50
ACC (AX_Z) 	= 1500
DEC (AX_Z) 	= 1500
KDEC(AX_Z) 	= 10000
JERK (AX_Z) = 50000

FMASK(AX_Z).#SRL 	= 1
FMASK(AX_Z).#SLL 	= 1
FDEF(AX_Z).#SRL 		= 1
FDEF(AX_Z).#SLL 		= 1						 
MFLAGS(AX_Z).#HOME = 1
DISP "Z HOMED"
DISP "BUFFER 3 STOPPED"
STOP 
#5
!PNAME=
!PDESC=
while M_Busy
X_AXIS = 0
Y_AXIS = 1
Z_AXIS = 4

!POINT A
PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT 1000

PTP/em (X_AXIS,Y_AXIS,AX_Z), 350, 25, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 50, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

PTP/em (X_AXIS,Y_AXIS,AX_Z), 300, 50, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE


!POINT B
PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 350, 250, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 275, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 300, 225, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000



!POINT C
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 75, 25, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 50, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 75, 50, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

!POINT D
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 75, 250, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 275, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 75, 225, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000



!POINT E
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 150, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 225, 150, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 150, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 175, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 150, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 225, 175, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 150, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000









END

STOP


#6
!PNAME=
!PDESC=
while M_Busy
X_AXIS = 0
Y_AXIS = 1
Z_AXIS = 4

! Extra program
INT WAIT_TIME = 500
INT WAIT_TIME_MOTION = 500
INT WAIT_TIME_LIGHT = 200


PTP/em (X_AXIS,Y_AXIS,AX_Z), 29.961563, 136.171738, 21.0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

	LOOP 33
		LED_OUT = 1
		WAIT 200
		LED_OUT = 0
		WAIT 200
	END


PTP/em (X_AXIS,Y_AXIS,AX_Z), 29.96293, 286.174258, 21.0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

	LOOP 33
		LED_OUT = 1
		WAIT 200
		LED_OUT = 0
		WAIT 200
	END


PTP/em (X_AXIS,Y_AXIS,AX_Z), 179.94541, 286.180391, 21.1499
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

	LOOP 33
		LED_OUT = 1
		WAIT 200
		LED_OUT = 0
		WAIT 200
	END




! GRID SEARCH PROGRAM - Row 1, Position 1
PTP/em (X_AXIS,Y_AXIS,AX_Z), 29.961563, 136.171738, 21.000000
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 2
PTP/em (X_AXIS,Y_AXIS,AX_Z), 30.961446, 136.171779, 21.000999
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 3
PTP/em (X_AXIS,Y_AXIS,AX_Z), 45.959694, 136.172392, 21.015989
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 4
PTP/em (X_AXIS,Y_AXIS,AX_Z), 60.957942, 136.173005, 21.030979
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 5
PTP/em (X_AXIS,Y_AXIS,AX_Z), 75.956190, 136.173619, 21.045969
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 6
PTP/em (X_AXIS,Y_AXIS,AX_Z), 90.954438, 136.174232, 21.060959
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT


! GRID SEARCH PROGRAM - Row 1, Position 7
PTP/em (X_AXIS,Y_AXIS,AX_Z), 105.952686, 136.174845, 21.075949
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 8
PTP/em (X_AXIS,Y_AXIS,AX_Z), 120.950934, 136.175459, 21.090939
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 9
PTP/em (X_AXIS,Y_AXIS,AX_Z), 135.949182, 136.176072, 21.105929
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 10
PTP/em (X_AXIS,Y_AXIS,AX_Z), 150.947430, 136.176685, 21.120919
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 11
PTP/em (X_AXIS,Y_AXIS,AX_Z), 165.945678, 136.177299, 21.135909
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 1, Position 12
PTP/em (X_AXIS,Y_AXIS,AX_Z), 166.945561, 136.177339, 21.136909
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT


! GRID SEARCH PROGRAM - Row 2, Position 1
PTP/em (X_AXIS,Y_AXIS,AX_Z), 29.961572, 137.171755, 21.000000
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT

! GRID SEARCH PROGRAM - Row 2, Position 2
PTP/em (X_AXIS,Y_AXIS,AX_Z), 30.961455, 137.171796, 21.000999
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT WAIT_TIME_MOTION

LED_OUT = 1
WAIT WAIT_TIME_LIGHT
LED_OUT = 0
WAIT WAIT_TIME_LIGHT





!POINT A
PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
WAIT 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 350, 25, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 50, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 300, 50, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

!POINT B
PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 350, 250, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 275, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 300, 225, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 325, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0


!POINT C
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 75, 25, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 50, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 75, 50, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 25, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

!POINT D
PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 75, 250, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 275, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 0
WAIT 300
LED_OUT = 1

PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 75, 225, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0

PTP/em (X_AXIS,Y_AXIS,AX_Z), 50, 250, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000

LED_OUT = 1
WAIT 300
LED_OUT = 0


!POINT E
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 150, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 225, 150, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 150, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 175, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 150, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 225, 175, 0
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000
PTP/em (X_AXIS,Y_AXIS,AX_Z), 200, 150, 10
TILL ^MST(AX_Z).#MOVE & ^MST(AX_Y).#MOVE & ^MST(AX_X_COG).#MOVE
wait 1000









END

STOP


#9
!PNAME=
!PDESC=
! Project 	: PKS003 - Demo room gantry 
! Date 		: 2025.07.30
! Script	: ACS motion paramerters and tuning parameters
! Author	: MalithJKD
! Motion units


VEL(0)	= 500
! Motion parameters
ACC(0) 	= 6000
DEC(0)	= 6000
JERK(0) = 13000

! Current loop
SLIKI(0) = 10000
SLIKP(0) = 1100

! PID 
SLPKP(0)	= 120 !150
SLPKI(0)	= 0
SLVKP(0)	= 500 !570
SLVKI(0)	= 420 !460	

MFLAGS(0).#NOFILT = 0 
SLVSOF(0)	= 460
SLVSOFD(0)	= 0.87

MFLAGS(0).#NOTCH = 0
SLVNFRQ(0) = 200
SLVNWID(0) = 4
SLVNATT(0) = 2

SLAFF(0)	= 220
SLJFF(0)	= 0.2
SLSFF(0)	= 0

! MST SETTLING WINDOW
! MST SETTLING WINDOW
TARGRAD(0) 	= 0.000050
SETTLE(0) 	= 2



! Project 	: PKS003 - Demo room gantry 
! Date 		: 2025.07.30
! Script	: ACS motion paramerters and tuning parameters
! Author	: MalithJKD
! Motion units


VEL(1)	= 500
! Motion parameters
ACC(1) 	= 6000
DEC(1)	= 6000
JERK(1) = 13000

! Current loop
SLIKI(1) = 150		!4000 
SLIKP(1) = 1500 	!1300 
! PID 
SLPKP(1)	= 150	!280
SLPKI(1)	= 100 	!0
SLVKP(1)	= 150	! 240 ! max 300 !570
SLVKI(1)	= 100	! 150 

MFLAGS(1).#NOFILT = 0 
SLVSOF(1)	= 300	!320 
SLVSOFD(1)	= 0.9

MFLAGS(1).#NOTCH = 0
SLVNFRQ(1) = 512 !200
SLVNWID(1) = 28
SLVNATT(1) = 3

SLAFF(1)	= 320	!270 
SLJFF(1)	= 0.3	!0.2
SLSFF(1)	= 0

! MST SETTLING WINDOW
! MST SETTLING WINDOW
TARGRAD(1) 	= 0.0001
SETTLE(1) 	= 2



! Project 	: PKS003 - Demo room gantry 
! Date 		: 2025.07.30
! Script	: ACS motion paramerters and tuning parameters
! Author	: MalithJKD
! Motion units


VEL(4)	= 5
! Motion parameters
ACC(4) 	= 100
DEC(4)	= 100
JERK(4) = 1000

STOP
#10
!PNAME=
!PDESC=
REAL STEP = 0

LOOP 2
	STEP = 0
	PTP/E 0,STEP
	LOOP 60
		PTP/E 0,STEP
		WAIT 5
		LED_OUT = 1
		WAIT 500
		LED_OUT = 0
		STEP = STEP + 5
	END
		
	
END

STOP
#27
!PNAME=
!PDESC=
! Define Variables

REAL AXIS_ARRAY(7)
REAL TOTAL_AXIS_COUNT
TOTAL_AXIS_COUNT = 6
REAL X
REAL Y = 0

! DEFINE AXIS ARRAY 
AXIS_ARRAY(0) = 0
AXIS_ARRAY(1) = 1
AXIS_ARRAY(2) = 2
AXIS_ARRAY(3) = 3
AXIS_ARRAY(4) = 4
AXIS_ARRAY(5) = 5
AXIS_ARRAY(6) = 6

! function based motion

DISP "ENABLE_ALL"
!GOTO ENABLE_ALL

WAIT 2000 

DISP "HOME_ALL"
GOTO HOME_ALL

WAIT 2000

DISP "PERFORM MOTION"
WAIT 2000




DISP "DISABLE_ALL"
! GOTO DISABLE_ALL
WAIT 2000
STOP


! FUNCTION 1
ENABLE_ALL:
	Y = 0	
	WHILE Y < TOTAL_AXIS_COUNT +1
		DISP "ENABLE", Y
		ENABLE Y 
		Y = Y +1 
		
		
	END 
	STOP

RET


! FUNCTION 2
HOME_ALL:
	START 3,1 ! Z HOME
	WAIT 2000
	START 1, 1 !Y HOME
	WAIT 2000 
	START 0,1 ! X HOME
	STOP
	WAIT 10000
RET



! FUNCTION 20
DISABLE_ALL:
	Y = 0	
	WHILE Y < TOTAL_AXIS_COUNT +1
		DISP "DISABLE", Y
		DISABLE Y 
		Y = Y +1 
		
		
	END 
	STOP
RET
#30
!PNAME=
!PDESC=
!PNAME=Tuning axis 0
!PDESC=
! Setup temparature sensors
! MalithJKD 
! 2025.07.14

! To start auto exiculte while switching on the motor 
AUTOEXEC:

! Define values 
int TempRep_offset_1,TempRep_offset_2,TempRep_offset_3, TempRep_offset_4, Device

! Slave number, Node, or device from ACS network or #ETHERCAT command
Device = 5

! get the "offset" value from "netowrk valriable name"
DISP "MAPPING TEMPRATURE SENSOR..."
TempRep_offset_1 = ECGETOFFSET("Input(s).Channel 1, Word 1", Device)  !#ETHERCAT 285
TempRep_offset_2 = ECGETOFFSET("Input(s).Channel 2, Word 1", Device)
TempRep_offset_3 = ECGETOFFSET("Input(s).Channel 3, Word 1", Device)
TempRep_offset_4 = ECGETOFFSET("Input(s).Channel 4, Word 1", Device)

! Actual mapping of the offset value to globally accesible variable 
ecin(TempRep_offset_1, Temparature_sensor_1)
ecin(TempRep_offset_2, Temparature_sensor_2)
ecin(TempRep_offset_3, Temparature_sensor_3)
ecin(TempRep_offset_4, Temparature_sensor_4)

!DISP TempRep_offset_1
!disp "TempRep: ", Temparature_sensor_1, Temparature_sensor_2,Temparature_sensor_3 

DISP "MAPPING TEMPRATURE SENSOR FINISHED."



INT OUT_Channel_1_Data_OFFSET

OUT_Channel_1_Data_OFFSET = ECGETOFFSET("Channel 1 Data", 5)

ECOUT(OUT_Channel_1_Data_OFFSET, LED_OUT)

DISP "MAPPING OUTPUT CHANNEL FINISHED."


STOP
#31
!PNAME=
!PDESC=
AUTOEXEC:

	DISP "Buffer 31 Auto Exec Started"
	DISP "Z AXIS DIGITAL INPUTS FOR LIMIT FUNCTION MAPPING"
	INT Z_ECOffset_DigitalInput
	Z_ECOffset_DigitalInput = ECGETOFFSET ("Digital Inputs" , 1)
	ECIN(Z_ECOffset_DigitalInput, Z_Digital_Input)
	
	!DELTA DIGITAL INPUTS AND OUTPUTS
	INT DELTA_IN_UNIT1_SLAVE_ID = 3
	INT DELTA_OUT_UNIT1_SLAVE_ID = 4
	
!	IF START_UP
!		DISP "START_UP so Call SetCommonSetting in Buffer 28"
!		Start CommonSetting, 1
!	ELSE
!		DISP "START_UP is 0; so Buffer 31 is called by host"
!	END
!	
	WAIT 300
	
	DISP "INPUT UNIT 1 UNPAMMING"
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,0))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,1))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,2))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,3))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,4))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,5))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,6))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,7))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,8))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,9))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,10))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,11))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,12))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,13))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,14))
	ECUNMAPIN(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,15))
	
	DISP "OUTPUT UNIT 1 UNPAMMING"
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,0))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,1))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,2))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,3))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,4))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,5))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,6))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,7))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,8))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,9))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,10))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,11))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,12))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,13))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,14))
	ECUNMAPOUT(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,15))
	
	DISP "DIGITAL INPUT UNIT 1 MAPPING"
	ECIN/b(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,1),Reset_Button_Bit)										!IN 0.0
	ECIN/b(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,2),Start_Button_Bit)										!IN 0.1
	ECIN/b(ECGETOFFSET/b("Input",DELTA_IN_UNIT1_SLAVE_ID,1,3),Stop_Button_Bit)						!IN 0.2
		
	!Outputs
	DISP "DIGITAL OUTPUT UNIT 1 MAPPING"
	ECOUT/b(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,1),ResetButtonLight_Bit)							!OUT 0.0
	ECOUT/b(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,2),StartButtonLight_Bit)							!OUT 0.1
	ECOUT/b(ECGETOFFSET/b("Output",DELTA_OUT_UNIT1_SLAVE_ID,0,3),StopButtonLight_Bit)							!OUT 0.2
	
IF START_UP = 0
	ResetButtonLight_Bit = 1
ELSE
	ResetButtonLight_Bit = 0
END
	
!AX_Z Left(-) limit sensor response initialization
IF Z_Digital_Input.17
	SAFINI(AX_Z).#LL=1
ELSE
	SAFINI(AX_Z).#LL=0
END

!AX_Z right(+) limit sensor response initialization
IF Z_Digital_Input.16
	SAFINI(AX_Z).#RL=1
ELSE
	SAFINI(AX_Z).#RL=0
END

STOP

! Z left limit
ON Z_Digital_Input.17 = 0
	SAFINI(AX_Z).#LL=0
RET
ON Z_Digital_Input.17 = 1
	SAFINI(AX_Z).#LL= 1
RET

! Z right limit
ON Z_Digital_Input.16 = 0
	SAFINI(AX_Z).#RL=0
RET
ON Z_Digital_Input.16 = 1
	SAFINI(AX_Z).#RL= 1
RET

Z_RESET:
	DISP "Z RESET"
	Z_ECOffset_ControlWord = ECGETOFFSET ("Controlword" , Z_Slave_Number)
	LOOP 2
		!*********Unmapping ethercat offset for control word******
		ECUNMAPIN(Z_ECOffset_ControlWord)
		ECUNMAPOUT(Z_ECOffset_ControlWord)
		!***************************************
		WAIT 300		
		DISP "Z Fault Clear"
		ECOUT(Z_ECOffset_ControlWord,ControlWord_Z)
		ControlWord_Z = 0x8F
		WAIT 300
		ControlWord_Z = 0x0F
		WAIT 300
	END
		
	ECUNMAPIN(Z_ECOffset_ControlWord)
	ECUNMAPOUT(Z_ECOffset_ControlWord)
	WAIT 300
RET

ON Reset_Button_Bit
	START 0,1
	TILL ^MST(AX_X_COG).#MOVE
	START 1,1
	TILL ^MST(AX_Y).#MOVE
	START 3,1
	TILL ^MST(AX_Z).#MOVE
	ResetButtonLight_Bit = 0
	WAIT 5000
	START_UP = 1
	M_Ready = 1
	StartButtonLight_Bit = 1
RET

ON Start_Button_Bit
	IF M_Ready
		StartButtonLight_Bit = 0
		StopButtonLight_Bit  = 1
		ResetButtonLight_Bit = 0
		START 5,1
		M_Busy 	= 1
		M_Ready = 0
		DISP "Start"
	ELSE
		DISP "Need To Reset"
	END
RET

ON Stop_Button_Bit
	IF M_Busy
		STOP 5
		KILL 0,1
		DISP "Stop All"
		M_Ready = 1
		M_Busy 	= 0
		StartButtonLight_Bit = 1
		StopButtonLight_Bit = 0
	END
RET
#A
!PNAME=
!PDESC=
GLOBAL REAL static CorrectionX(82)
GLOBAL REAL static CorrectionY(64)

GLOBAL INT I(100),I0,I1,I2,I3,I4,I5,I6,I7,I8,I9,I90,I91,I92,I93,I94,I95,I96,I97,I98,I99
GLOBAL REAL V(100),V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V90,V91,V92,V93,V94,V95,V96,V97,V98,V99

!homing variables
GLOBAL REAL HOME_VEL_IN(10)
GLOBAL REAL HOME_VEL_OUT(10)
GLOBAL REAL HOME_OFFSET(10)

GLOBAL INT X_AXIS = 0
GLOBAL INT Y_AXIS = 1
GLOBAL INT Z_AXIS = 4

AXISDEF AX_X_COG	= 0
AXISDEF AX_X_YAW	= 2
AXISDEF AX_Y		= 1
AXISDEF AX_Z		= 4

GLOBAL INT Z_Slave_Number		= 1

GLOBAL INT Z_ECOffset_ControlWord

GLOBAL INT START_UP = 0
GLOBAL INT M_Ready = 0
GLOBAL INT M_Busy = 0
GLOBAL INT M_Stop = 0

GLOBAL INT ECOFFSETM(3)

GLOBAL INT Z_Digital_Input
GLOBAL INT ControlWord_Z
GLOBAL INT ActualPos_Z

GLOBAL INT Z_Pos_Limits
GLOBAL INT Z_Neg_Limits

GLOBAL INT RedFlashing_Bit
GLOBAL INT YellowFlashing_Bit
GLOBAL INT GreenFlashing_Bit

!///////////////////////////////////////////////////////////
!Inputs

GLOBAL INT Reset_Button_Bit 								!I 0.1
GLOBAL INT Start_Button_Bit 								!I 0.2
GLOBAL INT Stop_Button_Bit									!I 0.3

!Outputs
GLOBAL INT ResetButtonLight_Bit 							! 0.0
GLOBAL INT StartButtonLight_Bit 							! 0.1
GLOBAL INT StopButtonLight_Bit 								! 0.2

!//////////////////////////////////////////////////////////

GLOBAL INT Gantry_Mode

! ////////////////////////////////////////////////////////
GLOBAL INT Temparature_sensor_1, Temparature_sensor_2, Temparature_sensor_3, Temparature_sensor_4

global static real Map1_correctionTable(8)(151);
global static real Map1_refAxis0_positions(151)
global static real Map1_refAxis1_positions(8)

global static real Map2_refAxis0_positions(151)
global static real Map2_refAxis1_positions(8)


! #VGV Map1_refAxis0_positions
STOP
global static real Map2_correctionTable(8)(151);


! WAGO OUTPUT
GLOBAL INT LED_OUT


STOP
