# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDockWidget, QFrame,
    QGroupBox, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1210, 760)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionMotion_Maneger = QAction(MainWindow)
        self.actionMotion_Maneger.setObjectName(u"actionMotion_Maneger")
        self.actionCamera_feedback = QAction(MainWindow)
        self.actionCamera_feedback.setObjectName(u"actionCamera_feedback")
        self.actionOpen_dot_locations = QAction(MainWindow)
        self.actionOpen_dot_locations.setObjectName(u"actionOpen_dot_locations")
        self.actionSave_dot_locations = QAction(MainWindow)
        self.actionSave_dot_locations.setObjectName(u"actionSave_dot_locations")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 380, 51))
        self.network_scan_button = QPushButton(self.groupBox)
        self.network_scan_button.setObjectName(u"network_scan_button")
        self.network_scan_button.setGeometry(QRect(10, 22, 79, 24))
        self.enable_communication_button = QPushButton(self.groupBox)
        self.enable_communication_button.setObjectName(u"enable_communication_button")
        self.enable_communication_button.setGeometry(QRect(236, 22, 131, 24))
        self.ip_input_lineEdit = QLineEdit(self.groupBox)
        self.ip_input_lineEdit.setObjectName(u"ip_input_lineEdit")
        self.ip_input_lineEdit.setGeometry(QRect(97, 23, 133, 22))
        self.ip_input_lineEdit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(199, 50, 91, 360))
        self.groupBox_3.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.select_axis_y_combo_box = QComboBox(self.groupBox_3)
        self.select_axis_y_combo_box.addItem("")
        self.select_axis_y_combo_box.addItem("")
        self.select_axis_y_combo_box.addItem("")
        self.select_axis_y_combo_box.addItem("")
        self.select_axis_y_combo_box.addItem("")
        self.select_axis_y_combo_box.addItem("")
        self.select_axis_y_combo_box.addItem("")
        self.select_axis_y_combo_box.addItem("")
        self.select_axis_y_combo_box.setObjectName(u"select_axis_y_combo_box")
        self.select_axis_y_combo_box.setGeometry(QRect(10, 20, 69, 22))
        self.select_axis_y_combo_box.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.select_axis_y_combo_box.setEditable(True)
        self.axis_y_fpos_lable = QLabel(self.groupBox_3)
        self.axis_y_fpos_lable.setObjectName(u"axis_y_fpos_lable")
        self.axis_y_fpos_lable.setGeometry(QRect(18, 80, 61, 20))
        self.axis_y_fpos_lable.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_y_fpos_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_y_set_position_line_edit = QLineEdit(self.groupBox_3)
        self.axis_y_set_position_line_edit.setObjectName(u"axis_y_set_position_line_edit")
        self.axis_y_set_position_line_edit.setGeometry(QRect(10, 50, 70, 20))
        self.axis_y_set_position_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_y_set_position_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_y_position_error = QLabel(self.groupBox_3)
        self.axis_y_position_error.setObjectName(u"axis_y_position_error")
        self.axis_y_position_error.setGeometry(QRect(18, 110, 61, 20))
        self.axis_y_position_error.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_y_position_error.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_y_enable_button = QPushButton(self.groupBox_3)
        self.axis_y_enable_button.setObjectName(u"axis_y_enable_button")
        self.axis_y_enable_button.setGeometry(QRect(10, 140, 70, 24))
        self.axis_y_enable_button.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.line_3 = QFrame(self.groupBox_3)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 130, 70, 3))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.groupBox_3)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(10, 170, 70, 3))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.axis_y_velocity_line_edit = QLineEdit(self.groupBox_3)
        self.axis_y_velocity_line_edit.setObjectName(u"axis_y_velocity_line_edit")
        self.axis_y_velocity_line_edit.setGeometry(QRect(10, 180, 70, 22))
        self.axis_y_velocity_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_y_velocity_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_y_acceleration_line_edit = QLineEdit(self.groupBox_3)
        self.axis_y_acceleration_line_edit.setObjectName(u"axis_y_acceleration_line_edit")
        self.axis_y_acceleration_line_edit.setGeometry(QRect(10, 210, 70, 22))
        self.axis_y_acceleration_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_y_acceleration_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_y_deceleration_line_edit = QLineEdit(self.groupBox_3)
        self.axis_y_deceleration_line_edit.setObjectName(u"axis_y_deceleration_line_edit")
        self.axis_y_deceleration_line_edit.setGeometry(QRect(10, 240, 70, 22))
        self.axis_y_deceleration_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_y_deceleration_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_y_kill_deceleration_line_edit = QLineEdit(self.groupBox_3)
        self.axis_y_kill_deceleration_line_edit.setObjectName(u"axis_y_kill_deceleration_line_edit")
        self.axis_y_kill_deceleration_line_edit.setGeometry(QRect(10, 270, 70, 22))
        self.axis_y_kill_deceleration_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_y_kill_deceleration_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_y_jerk_line_edit = QLineEdit(self.groupBox_3)
        self.axis_y_jerk_line_edit.setObjectName(u"axis_y_jerk_line_edit")
        self.axis_y_jerk_line_edit.setGeometry(QRect(10, 300, 70, 22))
        self.axis_y_jerk_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_y_jerk_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_y_motion_start_button = QPushButton(self.groupBox_3)
        self.axis_y_motion_start_button.setObjectName(u"axis_y_motion_start_button")
        self.axis_y_motion_start_button.setGeometry(QRect(10, 330, 70, 24))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 50, 180, 360))
        self.groupBox_2.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 22, 16))
        self.select_axis_x_combo_box = QComboBox(self.groupBox_2)
        self.select_axis_x_combo_box.addItem("")
        self.select_axis_x_combo_box.addItem("")
        self.select_axis_x_combo_box.addItem("")
        self.select_axis_x_combo_box.addItem("")
        self.select_axis_x_combo_box.addItem("")
        self.select_axis_x_combo_box.addItem("")
        self.select_axis_x_combo_box.addItem("")
        self.select_axis_x_combo_box.addItem("")
        self.select_axis_x_combo_box.setObjectName(u"select_axis_x_combo_box")
        self.select_axis_x_combo_box.setGeometry(QRect(100, 20, 69, 22))
        self.select_axis_x_combo_box.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.select_axis_x_combo_box.setEditable(True)
        self.axis_x_enable_button = QPushButton(self.groupBox_2)
        self.axis_x_enable_button.setObjectName(u"axis_x_enable_button")
        self.axis_x_enable_button.setGeometry(QRect(100, 140, 70, 24))
        self.axis_x_enable_button.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 80, 60, 20))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 50, 100, 16))
        self.axis_x_set_position_line_edit = QLineEdit(self.groupBox_2)
        self.axis_x_set_position_line_edit.setObjectName(u"axis_x_set_position_line_edit")
        self.axis_x_set_position_line_edit.setGeometry(QRect(100, 50, 70, 22))
        self.axis_x_set_position_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_x_set_position_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.line = QFrame(self.groupBox_2)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 170, 180, 3))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 110, 80, 16))
        self.axis_x_position_error = QLabel(self.groupBox_2)
        self.axis_x_position_error.setObjectName(u"axis_x_position_error")
        self.axis_x_position_error.setGeometry(QRect(98, 110, 71, 20))
        self.axis_x_position_error.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_x_position_error.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.line_2 = QFrame(self.groupBox_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 130, 180, 3))
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.axis_x_fpos_lable = QLabel(self.groupBox_2)
        self.axis_x_fpos_lable.setObjectName(u"axis_x_fpos_lable")
        self.axis_x_fpos_lable.setGeometry(QRect(98, 80, 71, 20))
        self.axis_x_fpos_lable.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_x_fpos_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 180, 49, 16))
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 210, 70, 16))
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 240, 80, 16))
        self.axis_x_velocity_line_edit = QLineEdit(self.groupBox_2)
        self.axis_x_velocity_line_edit.setObjectName(u"axis_x_velocity_line_edit")
        self.axis_x_velocity_line_edit.setGeometry(QRect(110, 180, 60, 22))
        self.axis_x_velocity_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_x_velocity_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_x_acceleration_line_edit = QLineEdit(self.groupBox_2)
        self.axis_x_acceleration_line_edit.setObjectName(u"axis_x_acceleration_line_edit")
        self.axis_x_acceleration_line_edit.setGeometry(QRect(110, 210, 60, 22))
        self.axis_x_acceleration_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_x_acceleration_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_x_deceleration_line_edit = QLineEdit(self.groupBox_2)
        self.axis_x_deceleration_line_edit.setObjectName(u"axis_x_deceleration_line_edit")
        self.axis_x_deceleration_line_edit.setGeometry(QRect(110, 240, 60, 22))
        self.axis_x_deceleration_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_x_deceleration_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 270, 90, 16))
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 300, 30, 16))
        self.axis_x_kill_deceleration_line_edit = QLineEdit(self.groupBox_2)
        self.axis_x_kill_deceleration_line_edit.setObjectName(u"axis_x_kill_deceleration_line_edit")
        self.axis_x_kill_deceleration_line_edit.setGeometry(QRect(110, 270, 60, 22))
        self.axis_x_kill_deceleration_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_x_kill_deceleration_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_x_jerk_line_edit = QLineEdit(self.groupBox_2)
        self.axis_x_jerk_line_edit.setObjectName(u"axis_x_jerk_line_edit")
        self.axis_x_jerk_line_edit.setGeometry(QRect(110, 300, 60, 22))
        self.axis_x_jerk_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_x_jerk_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_x_motion_start_button = QPushButton(self.groupBox_2)
        self.axis_x_motion_start_button.setObjectName(u"axis_x_motion_start_button")
        self.axis_x_motion_start_button.setGeometry(QRect(100, 330, 70, 24))
        self.label_23 = QLabel(self.groupBox_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 330, 70, 16))
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 140, 81, 16))
        self.emergency_stop_button = QPushButton(self.centralwidget)
        self.emergency_stop_button.setObjectName(u"emergency_stop_button")
        self.emergency_stop_button.setGeometry(QRect(10, 420, 381, 40))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(300, 50, 91, 360))
        self.groupBox_5.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.select_axis_z_combo_box = QComboBox(self.groupBox_5)
        self.select_axis_z_combo_box.addItem("")
        self.select_axis_z_combo_box.addItem("")
        self.select_axis_z_combo_box.addItem("")
        self.select_axis_z_combo_box.addItem("")
        self.select_axis_z_combo_box.addItem("")
        self.select_axis_z_combo_box.addItem("")
        self.select_axis_z_combo_box.addItem("")
        self.select_axis_z_combo_box.addItem("")
        self.select_axis_z_combo_box.setObjectName(u"select_axis_z_combo_box")
        self.select_axis_z_combo_box.setGeometry(QRect(10, 20, 69, 22))
        self.select_axis_z_combo_box.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.select_axis_z_combo_box.setEditable(True)
        self.axis_z_fpos_lable = QLabel(self.groupBox_5)
        self.axis_z_fpos_lable.setObjectName(u"axis_z_fpos_lable")
        self.axis_z_fpos_lable.setGeometry(QRect(8, 80, 71, 20))
        self.axis_z_fpos_lable.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_z_fpos_lable.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_z_set_position_line_edit = QLineEdit(self.groupBox_5)
        self.axis_z_set_position_line_edit.setObjectName(u"axis_z_set_position_line_edit")
        self.axis_z_set_position_line_edit.setGeometry(QRect(10, 50, 70, 20))
        self.axis_z_set_position_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_z_set_position_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_z_position_error = QLabel(self.groupBox_5)
        self.axis_z_position_error.setObjectName(u"axis_z_position_error")
        self.axis_z_position_error.setGeometry(QRect(8, 110, 71, 20))
        self.axis_z_position_error.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_z_position_error.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_z_enable_button = QPushButton(self.groupBox_5)
        self.axis_z_enable_button.setObjectName(u"axis_z_enable_button")
        self.axis_z_enable_button.setGeometry(QRect(10, 140, 70, 24))
        self.axis_z_enable_button.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.line_7 = QFrame(self.groupBox_5)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 130, 70, 3))
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_8 = QFrame(self.groupBox_5)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(10, 170, 70, 3))
        self.line_8.setFrameShape(QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.axis_z_velocity_line_edit = QLineEdit(self.groupBox_5)
        self.axis_z_velocity_line_edit.setObjectName(u"axis_z_velocity_line_edit")
        self.axis_z_velocity_line_edit.setGeometry(QRect(10, 180, 70, 22))
        self.axis_z_velocity_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_z_velocity_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_z_acceleration_line_edit = QLineEdit(self.groupBox_5)
        self.axis_z_acceleration_line_edit.setObjectName(u"axis_z_acceleration_line_edit")
        self.axis_z_acceleration_line_edit.setGeometry(QRect(10, 210, 70, 22))
        self.axis_z_acceleration_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_z_acceleration_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_z_deceleration_line_edit = QLineEdit(self.groupBox_5)
        self.axis_z_deceleration_line_edit.setObjectName(u"axis_z_deceleration_line_edit")
        self.axis_z_deceleration_line_edit.setGeometry(QRect(10, 240, 70, 22))
        self.axis_z_deceleration_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_z_deceleration_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_z_kill_deceleration_line_edit = QLineEdit(self.groupBox_5)
        self.axis_z_kill_deceleration_line_edit.setObjectName(u"axis_z_kill_deceleration_line_edit")
        self.axis_z_kill_deceleration_line_edit.setGeometry(QRect(10, 270, 70, 22))
        self.axis_z_kill_deceleration_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_z_kill_deceleration_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_z_jerk_line_edit = QLineEdit(self.groupBox_5)
        self.axis_z_jerk_line_edit.setObjectName(u"axis_z_jerk_line_edit")
        self.axis_z_jerk_line_edit.setGeometry(QRect(10, 300, 70, 22))
        self.axis_z_jerk_line_edit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.axis_z_jerk_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.axis_z_motion_start_button = QPushButton(self.groupBox_5)
        self.axis_z_motion_start_button.setObjectName(u"axis_z_motion_start_button")
        self.axis_z_motion_start_button.setGeometry(QRect(10, 330, 70, 24))
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(660, 10, 540, 461))
        self.table_widget = QTableWidget(self.groupBox_6)
        self.table_widget.setObjectName(u"table_widget")
        self.table_widget.setGeometry(QRect(10, 20, 520, 430))
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 480, 381, 171))
        self.in_position_test_start_button = QPushButton(self.groupBox_7)
        self.in_position_test_start_button.setObjectName(u"in_position_test_start_button")
        self.in_position_test_start_button.setGeometry(QRect(310, 30, 60, 24))
        self.label_19 = QLabel(self.groupBox_7)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 30, 101, 21))
        self.number_of_image_line_edit = QLineEdit(self.groupBox_7)
        self.number_of_image_line_edit.setObjectName(u"number_of_image_line_edit")
        self.number_of_image_line_edit.setGeometry(QRect(200, 30, 70, 22))
        self.number_of_image_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_20 = QLabel(self.groupBox_7)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 70, 181, 21))
        self.label_sigma_R = QLabel(self.groupBox_7)
        self.label_sigma_R.setObjectName(u"label_sigma_R")
        self.label_sigma_R.setGeometry(QRect(201, 70, 71, 21))
        self.label_22 = QLabel(self.groupBox_7)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 100, 181, 21))
        self.label_24 = QLabel(self.groupBox_7)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 130, 181, 21))
        self.label_sigma_X = QLabel(self.groupBox_7)
        self.label_sigma_X.setObjectName(u"label_sigma_X")
        self.label_sigma_X.setGeometry(QRect(200, 100, 71, 21))
        self.label_sigma_Y = QLabel(self.groupBox_7)
        self.label_sigma_Y.setObjectName(u"label_sigma_Y")
        self.label_sigma_Y.setGeometry(QRect(200, 130, 71, 21))
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(660, 480, 541, 171))
        self.label_15 = QLabel(self.groupBox_8)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 30, 171, 16))
        self.label_16 = QLabel(self.groupBox_8)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 60, 171, 16))
        self.label_17 = QLabel(self.groupBox_8)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 90, 171, 16))
        self.start_temperature_sensor_button = QPushButton(self.groupBox_8)
        self.start_temperature_sensor_button.setObjectName(u"start_temperature_sensor_button")
        self.start_temperature_sensor_button.setGeometry(QRect(10, 140, 160, 24))
        self.label_31 = QLabel(self.groupBox_8)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 120, 170, 16))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(400, 10, 251, 541))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox_9 = QGroupBox(self.tab)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(0, 370, 231, 141))
        self.label_32 = QLabel(self.groupBox_9)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 30, 130, 20))
        self.pitch_input_row_y = QLineEdit(self.groupBox_9)
        self.pitch_input_row_y.setObjectName(u"pitch_input_row_y")
        self.pitch_input_row_y.setGeometry(QRect(170, 30, 50, 22))
        self.pitch_input_row_y.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pitch_input_row_y.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_28 = QLabel(self.groupBox_9)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 60, 140, 20))
        self.pitch_input_column_x = QLineEdit(self.groupBox_9)
        self.pitch_input_column_x.setObjectName(u"pitch_input_column_x")
        self.pitch_input_column_x.setGeometry(QRect(170, 60, 50, 22))
        self.pitch_input_column_x.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.update_varible_pitch_button = QPushButton(self.groupBox_9)
        self.update_varible_pitch_button.setObjectName(u"update_varible_pitch_button")
        self.update_varible_pitch_button.setGeometry(QRect(10, 100, 210, 30))
        self.groupBox_10 = QGroupBox(self.tab)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(0, 20, 231, 131))
        self.calibration_data_table_create = QPushButton(self.groupBox_10)
        self.calibration_data_table_create.setObjectName(u"calibration_data_table_create")
        self.calibration_data_table_create.setGeometry(QRect(10, 90, 210, 30))
        self.calibration_data_table_row_input = QLineEdit(self.groupBox_10)
        self.calibration_data_table_row_input.setObjectName(u"calibration_data_table_row_input")
        self.calibration_data_table_row_input.setGeometry(QRect(130, 30, 90, 21))
        self.label_7 = QLabel(self.groupBox_10)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 110, 16))
        self.calibration_data_table_column_input = QLineEdit(self.groupBox_10)
        self.calibration_data_table_column_input.setObjectName(u"calibration_data_table_column_input")
        self.calibration_data_table_column_input.setGeometry(QRect(130, 60, 90, 20))
        self.label_13 = QLabel(self.groupBox_10)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 60, 80, 16))
        self.groupBox_11 = QGroupBox(self.tab)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(0, 150, 231, 220))
        self.label_14 = QLabel(self.groupBox_11)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 30, 110, 16))
        self.move_to_position_push_button = QPushButton(self.groupBox_11)
        self.move_to_position_push_button.setObjectName(u"move_to_position_push_button")
        self.move_to_position_push_button.setGeometry(QRect(10, 140, 101, 30))
        self.dot_center_estimate_button = QPushButton(self.groupBox_11)
        self.dot_center_estimate_button.setObjectName(u"dot_center_estimate_button")
        self.dot_center_estimate_button.setGeometry(QRect(10, 100, 210, 30))
        self.display_coodinate_combo_box = QComboBox(self.groupBox_11)
        self.display_coodinate_combo_box.addItem("")
        self.display_coodinate_combo_box.addItem("")
        self.display_coodinate_combo_box.addItem("")
        self.display_coodinate_combo_box.setObjectName(u"display_coodinate_combo_box")
        self.display_coodinate_combo_box.setGeometry(QRect(130, 30, 90, 22))
        self.calculate_grid_locations_push_button = QPushButton(self.groupBox_11)
        self.calculate_grid_locations_push_button.setObjectName(u"calculate_grid_locations_push_button")
        self.calculate_grid_locations_push_button.setGeometry(QRect(120, 180, 101, 30))
        self.select_camera_mode_button = QPushButton(self.groupBox_11)
        self.select_camera_mode_button.setObjectName(u"select_camera_mode_button")
        self.select_camera_mode_button.setGeometry(QRect(10, 60, 211, 30))
        self.auto_focus_button = QPushButton(self.groupBox_11)
        self.auto_focus_button.setObjectName(u"auto_focus_button")
        self.auto_focus_button.setGeometry(QRect(120, 140, 101, 30))
        self.get_x_y_value_push_button = QPushButton(self.groupBox_11)
        self.get_x_y_value_push_button.setObjectName(u"get_x_y_value_push_button")
        self.get_x_y_value_push_button.setGeometry(QRect(10, 180, 101, 30))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_12 = QGroupBox(self.tab_2)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(0, 20, 231, 470))
        self.select_test_axis_combo_box = QComboBox(self.groupBox_12)
        self.select_test_axis_combo_box.addItem("")
        self.select_test_axis_combo_box.addItem("")
        self.select_test_axis_combo_box.setObjectName(u"select_test_axis_combo_box")
        self.select_test_axis_combo_box.setGeometry(QRect(110, 80, 110, 22))
        self.label_25 = QLabel(self.groupBox_12)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 80, 81, 21))
        self.select_test_combo_box = QComboBox(self.groupBox_12)
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.addItem("")
        self.select_test_combo_box.setObjectName(u"select_test_combo_box")
        self.select_test_combo_box.setGeometry(QRect(10, 50, 210, 21))
        self.label_21 = QLabel(self.groupBox_12)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 30, 61, 21))
        self.scan_button = QPushButton(self.groupBox_12)
        self.scan_button.setObjectName(u"scan_button")
        self.scan_button.setGeometry(QRect(10, 430, 211, 30))
        self.label_30 = QLabel(self.groupBox_12)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 200, 100, 20))
        self.label_26 = QLabel(self.groupBox_12)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 110, 80, 20))
        self.label_29 = QLabel(self.groupBox_12)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 170, 91, 20))
        self.wait_time_line_edit = QLineEdit(self.groupBox_12)
        self.wait_time_line_edit.setObjectName(u"wait_time_line_edit")
        self.wait_time_line_edit.setGeometry(QRect(110, 230, 110, 22))
        self.wait_time_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.last_target_line_edit = QLineEdit(self.groupBox_12)
        self.last_target_line_edit.setObjectName(u"last_target_line_edit")
        self.last_target_line_edit.setGeometry(QRect(110, 140, 110, 22))
        self.last_target_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.number_of_runs_line_edit = QLineEdit(self.groupBox_12)
        self.number_of_runs_line_edit.setObjectName(u"number_of_runs_line_edit")
        self.number_of_runs_line_edit.setGeometry(QRect(110, 170, 110, 22))
        self.number_of_runs_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.number_of_inspection_images_line_edit = QLineEdit(self.groupBox_12)
        self.number_of_inspection_images_line_edit.setObjectName(u"number_of_inspection_images_line_edit")
        self.number_of_inspection_images_line_edit.setGeometry(QRect(110, 200, 110, 22))
        self.number_of_inspection_images_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_27 = QLabel(self.groupBox_12)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 140, 90, 16))
        self.label_33 = QLabel(self.groupBox_12)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 230, 100, 20))
        self.first_target_line_edit = QLineEdit(self.groupBox_12)
        self.first_target_line_edit.setObjectName(u"first_target_line_edit")
        self.first_target_line_edit.setGeometry(QRect(110, 110, 110, 22))
        self.first_target_line_edit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_13 = QGroupBox(self.tab_3)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(0, 20, 231, 471))
        self.file_input_1_line_edit = QLineEdit(self.groupBox_13)
        self.file_input_1_line_edit.setObjectName(u"file_input_1_line_edit")
        self.file_input_1_line_edit.setGeometry(QRect(10, 110, 211, 20))
        self.file_input_1_button = QPushButton(self.groupBox_13)
        self.file_input_1_button.setObjectName(u"file_input_1_button")
        self.file_input_1_button.setGeometry(QRect(10, 80, 211, 24))
        self.file_input_2_button = QPushButton(self.groupBox_13)
        self.file_input_2_button.setObjectName(u"file_input_2_button")
        self.file_input_2_button.setGeometry(QRect(10, 150, 210, 24))
        self.file_input_2_line_edit = QLineEdit(self.groupBox_13)
        self.file_input_2_line_edit.setObjectName(u"file_input_2_line_edit")
        self.file_input_2_line_edit.setGeometry(QRect(10, 180, 210, 22))
        self.file_input_3_button = QPushButton(self.groupBox_13)
        self.file_input_3_button.setObjectName(u"file_input_3_button")
        self.file_input_3_button.setGeometry(QRect(10, 220, 211, 24))
        self.file_input_3_line_edit = QLineEdit(self.groupBox_13)
        self.file_input_3_line_edit.setObjectName(u"file_input_3_line_edit")
        self.file_input_3_line_edit.setGeometry(QRect(11, 250, 210, 22))
        self.file_input_4_button = QPushButton(self.groupBox_13)
        self.file_input_4_button.setObjectName(u"file_input_4_button")
        self.file_input_4_button.setGeometry(QRect(10, 290, 210, 24))
        self.file_input_4_line_edit = QLineEdit(self.groupBox_13)
        self.file_input_4_line_edit.setObjectName(u"file_input_4_line_edit")
        self.file_input_4_line_edit.setGeometry(QRect(10, 320, 210, 22))
        self.run_action_button = QPushButton(self.groupBox_13)
        self.run_action_button.setObjectName(u"run_action_button")
        self.run_action_button.setGeometry(QRect(10, 430, 210, 30))
        self.label_34 = QLabel(self.groupBox_13)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(20, 20, 80, 16))
        self.select_action_combo_box = QComboBox(self.groupBox_13)
        self.select_action_combo_box.addItem("")
        self.select_action_combo_box.addItem("")
        self.select_action_combo_box.addItem("")
        self.select_action_combo_box.addItem("")
        self.select_action_combo_box.addItem("")
        self.select_action_combo_box.addItem("")
        self.select_action_combo_box.addItem("")
        self.select_action_combo_box.setObjectName(u"select_action_combo_box")
        self.select_action_combo_box.setGeometry(QRect(10, 40, 211, 22))
        self.line_5 = QFrame(self.groupBox_13)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 280, 230, 3))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(self.groupBox_13)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(0, 210, 230, 3))
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_9 = QFrame(self.groupBox_13)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(0, 140, 230, 3))
        self.line_9.setFrameShape(QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_10 = QFrame(self.groupBox_13)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(0, 70, 230, 3))
        self.line_10.setFrameShape(QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_11 = QFrame(self.groupBox_13)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(0, 350, 230, 3))
        self.line_11.setFrameShape(QFrame.Shape.HLine)
        self.line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.tabWidget.addTab(self.tab_3, "")
        self.info_text_edit = QTextEdit(self.centralwidget)
        self.info_text_edit.setObjectName(u"info_text_edit")
        self.info_text_edit.setGeometry(QRect(400, 560, 241, 91))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 2909, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuOpen = QMenu(self.menuFile)
        self.menuOpen.setObjectName(u"menuOpen")
        self.menuSave = QMenu(self.menuFile)
        self.menuSave.setObjectName(u"menuSave")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.cam_dock_widget = QDockWidget(MainWindow)
        self.cam_dock_widget.setObjectName(u"cam_dock_widget")
        self.cam_dock_widget.setMinimumSize(QSize(1200, 900))
        self.cam_dock_widget.setFloating(True)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.groupBox_4 = QGroupBox(self.dockWidgetContents_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(100, 0, 1250, 901))
        self.cam_input_lable = QLabel(self.groupBox_4)
        self.cam_input_lable.setObjectName(u"cam_input_lable")
        self.cam_input_lable.setGeometry(QRect(10, 20, 1090, 861))
        self.label_3 = QLabel(self.dockWidgetContents_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 80, 21))
        self.cam_type_combo_box = QComboBox(self.dockWidgetContents_2)
        self.cam_type_combo_box.addItem("")
        self.cam_type_combo_box.addItem("")
        self.cam_type_combo_box.addItem("")
        self.cam_type_combo_box.addItem("")
        self.cam_type_combo_box.setObjectName(u"cam_type_combo_box")
        self.cam_type_combo_box.setGeometry(QRect(10, 30, 81, 22))
        self.select_circle_radio_button = QRadioButton(self.dockWidgetContents_2)
        self.select_circle_radio_button.setObjectName(u"select_circle_radio_button")
        self.select_circle_radio_button.setGeometry(QRect(10, 230, 81, 30))
        self.label_18 = QLabel(self.dockWidgetContents_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 60, 80, 21))
        self.cam_id_combo_box = QComboBox(self.dockWidgetContents_2)
        self.cam_id_combo_box.addItem("")
        self.cam_id_combo_box.addItem("")
        self.cam_id_combo_box.addItem("")
        self.cam_id_combo_box.addItem("")
        self.cam_id_combo_box.setObjectName(u"cam_id_combo_box")
        self.cam_id_combo_box.setGeometry(QRect(10, 80, 81, 22))
        self.start_camera_push_button = QPushButton(self.dockWidgetContents_2)
        self.start_camera_push_button.setObjectName(u"start_camera_push_button")
        self.start_camera_push_button.setGeometry(QRect(10, 110, 81, 24))
        self.stop_camera_push_button = QPushButton(self.dockWidgetContents_2)
        self.stop_camera_push_button.setObjectName(u"stop_camera_push_button")
        self.stop_camera_push_button.setGeometry(QRect(10, 170, 81, 24))
        self.save_image_push_button = QPushButton(self.dockWidgetContents_2)
        self.save_image_push_button.setObjectName(u"save_image_push_button")
        self.save_image_push_button.setGeometry(QRect(10, 140, 81, 24))
        self.cam_dock_widget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.cam_dock_widget)
        QWidget.setTabOrder(self.network_scan_button, self.ip_input_lineEdit)
        QWidget.setTabOrder(self.ip_input_lineEdit, self.enable_communication_button)
        QWidget.setTabOrder(self.enable_communication_button, self.select_axis_x_combo_box)
        QWidget.setTabOrder(self.select_axis_x_combo_box, self.axis_x_set_position_line_edit)
        QWidget.setTabOrder(self.axis_x_set_position_line_edit, self.axis_x_velocity_line_edit)
        QWidget.setTabOrder(self.axis_x_velocity_line_edit, self.axis_x_acceleration_line_edit)
        QWidget.setTabOrder(self.axis_x_acceleration_line_edit, self.axis_x_deceleration_line_edit)
        QWidget.setTabOrder(self.axis_x_deceleration_line_edit, self.axis_x_kill_deceleration_line_edit)
        QWidget.setTabOrder(self.axis_x_kill_deceleration_line_edit, self.axis_x_jerk_line_edit)
        QWidget.setTabOrder(self.axis_x_jerk_line_edit, self.axis_x_enable_button)
        QWidget.setTabOrder(self.axis_x_enable_button, self.axis_x_motion_start_button)
        QWidget.setTabOrder(self.axis_x_motion_start_button, self.select_axis_y_combo_box)
        QWidget.setTabOrder(self.select_axis_y_combo_box, self.axis_y_set_position_line_edit)
        QWidget.setTabOrder(self.axis_y_set_position_line_edit, self.axis_y_velocity_line_edit)
        QWidget.setTabOrder(self.axis_y_velocity_line_edit, self.axis_y_acceleration_line_edit)
        QWidget.setTabOrder(self.axis_y_acceleration_line_edit, self.axis_y_deceleration_line_edit)
        QWidget.setTabOrder(self.axis_y_deceleration_line_edit, self.axis_y_kill_deceleration_line_edit)
        QWidget.setTabOrder(self.axis_y_kill_deceleration_line_edit, self.axis_y_jerk_line_edit)
        QWidget.setTabOrder(self.axis_y_jerk_line_edit, self.axis_y_enable_button)
        QWidget.setTabOrder(self.axis_y_enable_button, self.axis_y_motion_start_button)
        QWidget.setTabOrder(self.axis_y_motion_start_button, self.select_axis_z_combo_box)
        QWidget.setTabOrder(self.select_axis_z_combo_box, self.axis_z_set_position_line_edit)
        QWidget.setTabOrder(self.axis_z_set_position_line_edit, self.axis_z_velocity_line_edit)
        QWidget.setTabOrder(self.axis_z_velocity_line_edit, self.axis_z_acceleration_line_edit)
        QWidget.setTabOrder(self.axis_z_acceleration_line_edit, self.axis_z_deceleration_line_edit)
        QWidget.setTabOrder(self.axis_z_deceleration_line_edit, self.axis_z_kill_deceleration_line_edit)
        QWidget.setTabOrder(self.axis_z_kill_deceleration_line_edit, self.axis_z_jerk_line_edit)
        QWidget.setTabOrder(self.axis_z_jerk_line_edit, self.axis_z_enable_button)
        QWidget.setTabOrder(self.axis_z_enable_button, self.axis_z_motion_start_button)
        QWidget.setTabOrder(self.axis_z_motion_start_button, self.emergency_stop_button)
        QWidget.setTabOrder(self.emergency_stop_button, self.calibration_data_table_row_input)
        QWidget.setTabOrder(self.calibration_data_table_row_input, self.calibration_data_table_column_input)
        QWidget.setTabOrder(self.calibration_data_table_column_input, self.calibration_data_table_create)
        QWidget.setTabOrder(self.calibration_data_table_create, self.table_widget)
        QWidget.setTabOrder(self.table_widget, self.display_coodinate_combo_box)
        QWidget.setTabOrder(self.display_coodinate_combo_box, self.get_x_y_value_push_button)
        QWidget.setTabOrder(self.get_x_y_value_push_button, self.move_to_position_push_button)
        QWidget.setTabOrder(self.move_to_position_push_button, self.calculate_grid_locations_push_button)
        QWidget.setTabOrder(self.calculate_grid_locations_push_button, self.scan_button)
        QWidget.setTabOrder(self.scan_button, self.start_temperature_sensor_button)
        QWidget.setTabOrder(self.start_temperature_sensor_button, self.cam_type_combo_box)
        QWidget.setTabOrder(self.cam_type_combo_box, self.cam_id_combo_box)
        QWidget.setTabOrder(self.cam_id_combo_box, self.start_camera_push_button)
        QWidget.setTabOrder(self.start_camera_push_button, self.stop_camera_push_button)
        QWidget.setTabOrder(self.stop_camera_push_button, self.select_circle_radio_button)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuOpen.addAction(self.actionOpen_dot_locations)
        self.menuSave.addAction(self.actionSave_dot_locations)
        self.menuView.addAction(self.actionCamera_feedback)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PBA Vision", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionMotion_Maneger.setText(QCoreApplication.translate("MainWindow", u"Motion Maneger", None))
        self.actionCamera_feedback.setText(QCoreApplication.translate("MainWindow", u"Camera feedback", None))
        self.actionOpen_dot_locations.setText(QCoreApplication.translate("MainWindow", u"Open dot locations", None))
        self.actionSave_dot_locations.setText(QCoreApplication.translate("MainWindow", u"Save dot locations", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Communication", None))
        self.network_scan_button.setText(QCoreApplication.translate("MainWindow", u"Scan network", None))
        self.enable_communication_button.setText(QCoreApplication.translate("MainWindow", u"Enable communication", None))
        self.ip_input_lineEdit.setText(QCoreApplication.translate("MainWindow", u"0.0.0.0", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Y Axis Control", None))
        self.select_axis_y_combo_box.setItemText(0, "")
        self.select_axis_y_combo_box.setItemText(1, QCoreApplication.translate("MainWindow", u"0", None))
        self.select_axis_y_combo_box.setItemText(2, QCoreApplication.translate("MainWindow", u"1", None))
        self.select_axis_y_combo_box.setItemText(3, QCoreApplication.translate("MainWindow", u"2", None))
        self.select_axis_y_combo_box.setItemText(4, QCoreApplication.translate("MainWindow", u"3", None))
        self.select_axis_y_combo_box.setItemText(5, QCoreApplication.translate("MainWindow", u"4", None))
        self.select_axis_y_combo_box.setItemText(6, QCoreApplication.translate("MainWindow", u"5", None))
        self.select_axis_y_combo_box.setItemText(7, QCoreApplication.translate("MainWindow", u"6", None))

        self.select_axis_y_combo_box.setCurrentText("")
        self.axis_y_fpos_lable.setText(QCoreApplication.translate("MainWindow", u"0.0000", None))
        self.axis_y_set_position_line_edit.setText(QCoreApplication.translate("MainWindow", u"0.0000", None))
        self.axis_y_position_error.setText(QCoreApplication.translate("MainWindow", u"0.0000", None))
        self.axis_y_enable_button.setText(QCoreApplication.translate("MainWindow", u"Enable", None))
        self.axis_y_velocity_line_edit.setInputMask("")
        self.axis_y_velocity_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_y_acceleration_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_y_deceleration_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_y_kill_deceleration_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_y_jerk_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_y_motion_start_button.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"X Axis Control", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Axis", None))
        self.select_axis_x_combo_box.setItemText(0, "")
        self.select_axis_x_combo_box.setItemText(1, QCoreApplication.translate("MainWindow", u"0", None))
        self.select_axis_x_combo_box.setItemText(2, QCoreApplication.translate("MainWindow", u"1", None))
        self.select_axis_x_combo_box.setItemText(3, QCoreApplication.translate("MainWindow", u"2", None))
        self.select_axis_x_combo_box.setItemText(4, QCoreApplication.translate("MainWindow", u"3", None))
        self.select_axis_x_combo_box.setItemText(5, QCoreApplication.translate("MainWindow", u"4", None))
        self.select_axis_x_combo_box.setItemText(6, QCoreApplication.translate("MainWindow", u"5", None))
        self.select_axis_x_combo_box.setItemText(7, QCoreApplication.translate("MainWindow", u"6", None))

        self.select_axis_x_combo_box.setCurrentText("")
        self.axis_x_enable_button.setText(QCoreApplication.translate("MainWindow", u"Enable", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Feedback", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Move To", None))
        self.axis_x_set_position_line_edit.setText(QCoreApplication.translate("MainWindow", u"0.0000", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Position error", None))
        self.axis_x_position_error.setText(QCoreApplication.translate("MainWindow", u"0.0000", None))
        self.axis_x_fpos_lable.setText(QCoreApplication.translate("MainWindow", u"0.0000", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Velocity", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Accleration", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Deceleration", None))
        self.axis_x_velocity_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_x_acceleration_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_x_deceleration_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Kill Deceleration", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Jerk", None))
        self.axis_x_kill_deceleration_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_x_jerk_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_x_motion_start_button.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Motion start", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Motor state", None))
        self.emergency_stop_button.setText(QCoreApplication.translate("MainWindow", u"STOP & DISABLE ALL", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Z Axis Control", None))
        self.select_axis_z_combo_box.setItemText(0, "")
        self.select_axis_z_combo_box.setItemText(1, QCoreApplication.translate("MainWindow", u"0", None))
        self.select_axis_z_combo_box.setItemText(2, QCoreApplication.translate("MainWindow", u"1", None))
        self.select_axis_z_combo_box.setItemText(3, QCoreApplication.translate("MainWindow", u"2", None))
        self.select_axis_z_combo_box.setItemText(4, QCoreApplication.translate("MainWindow", u"3", None))
        self.select_axis_z_combo_box.setItemText(5, QCoreApplication.translate("MainWindow", u"4", None))
        self.select_axis_z_combo_box.setItemText(6, QCoreApplication.translate("MainWindow", u"5", None))
        self.select_axis_z_combo_box.setItemText(7, QCoreApplication.translate("MainWindow", u"6", None))

        self.select_axis_z_combo_box.setCurrentText("")
        self.axis_z_fpos_lable.setText(QCoreApplication.translate("MainWindow", u"0.0000", None))
        self.axis_z_set_position_line_edit.setText(QCoreApplication.translate("MainWindow", u"0.0000", None))
        self.axis_z_position_error.setText(QCoreApplication.translate("MainWindow", u"0.0000", None))
        self.axis_z_enable_button.setText(QCoreApplication.translate("MainWindow", u"Enable", None))
        self.axis_z_velocity_line_edit.setInputMask("")
        self.axis_z_velocity_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_z_acceleration_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_z_deceleration_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_z_kill_deceleration_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_z_jerk_line_edit.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.axis_z_motion_start_button.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Error mapping test - (Calibration data)", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"In position test", None))
        self.in_position_test_start_button.setText(QCoreApplication.translate("MainWindow", u"Start test", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Number of images", None))
        self.number_of_image_line_edit.setText(QCoreApplication.translate("MainWindow", u"32", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Raduis calculation 3\u03c3", None))
        self.label_sigma_R.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"X position calculation 3\u03c3 ", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Y position calculation 3\u03c3", None))
        self.label_sigma_X.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_sigma_Y.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Temparature sensors", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Temparature sensor 1 : 00.00 \u00b0C", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Temparature sensor 2 : 00.00 \u00b0C ", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Temparature sensor 3 : 00.00 \u00b0C ", None))
        self.start_temperature_sensor_button.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Temparature sensor 4 : 00.00 \u00b0C ", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Change pitch", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Scanning pitch rows (Y)", None))
        self.pitch_input_row_y.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Scanning pitch column (X)", None))
        self.pitch_input_column_x.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.update_varible_pitch_button.setText(QCoreApplication.translate("MainWindow", u"Create and save table", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Create table", None))
        self.calibration_data_table_create.setText(QCoreApplication.translate("MainWindow", u"Create table", None))
        self.calibration_data_table_row_input.setText(QCoreApplication.translate("MainWindow", u"151", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Rows ( Y ) of targets", None))
        self.calibration_data_table_column_input.setText(QCoreApplication.translate("MainWindow", u"151", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Columns ( X )", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Aligning glass ", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Display codinates", None))
        self.move_to_position_push_button.setText(QCoreApplication.translate("MainWindow", u"Move to position", None))
        self.dot_center_estimate_button.setText(QCoreApplication.translate("MainWindow", u"Estimate dot center location", None))
        self.display_coodinate_combo_box.setItemText(0, QCoreApplication.translate("MainWindow", u"X axis", None))
        self.display_coodinate_combo_box.setItemText(1, QCoreApplication.translate("MainWindow", u"Y axis", None))
        self.display_coodinate_combo_box.setItemText(2, QCoreApplication.translate("MainWindow", u"Z axis", None))

        self.calculate_grid_locations_push_button.setText(QCoreApplication.translate("MainWindow", u"Calculate grid", None))
        self.select_camera_mode_button.setText(QCoreApplication.translate("MainWindow", u"Camere mode: Teach", None))
        self.auto_focus_button.setText(QCoreApplication.translate("MainWindow", u"Auto-forcus", None))
        self.get_x_y_value_push_button.setText(QCoreApplication.translate("MainWindow", u"Update position", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Create table", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Testing error mapping", None))
        self.select_test_axis_combo_box.setItemText(0, QCoreApplication.translate("MainWindow", u"X axis", None))
        self.select_test_axis_combo_box.setItemText(1, QCoreApplication.translate("MainWindow", u"Y axis", None))

        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Select axis", None))
        self.select_test_combo_box.setItemText(0, QCoreApplication.translate("MainWindow", u"1D error map X axis", None))
        self.select_test_combo_box.setItemText(1, QCoreApplication.translate("MainWindow", u"1D error map Y axis", None))
        self.select_test_combo_box.setItemText(2, QCoreApplication.translate("MainWindow", u"2D error map", None))
        self.select_test_combo_box.setItemText(3, QCoreApplication.translate("MainWindow", u"1D expantion X axis", None))
        self.select_test_combo_box.setItemText(4, QCoreApplication.translate("MainWindow", u"1D expantion Y axis", None))
        self.select_test_combo_box.setItemText(5, QCoreApplication.translate("MainWindow", u"2D expantion", None))
        self.select_test_combo_box.setItemText(6, QCoreApplication.translate("MainWindow", u"Expantion in position static", None))
        self.select_test_combo_box.setItemText(7, QCoreApplication.translate("MainWindow", u"Expantion in position dynamic", None))
        self.select_test_combo_box.setItemText(8, QCoreApplication.translate("MainWindow", u"Auto focus X axis", None))
        self.select_test_combo_box.setItemText(9, QCoreApplication.translate("MainWindow", u"Motion Distance Calculation #54", None))

        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Select test", None))
        self.scan_button.setText(QCoreApplication.translate("MainWindow", u"Scan", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Number of images", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"First target", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Number of runs", None))
        self.wait_time_line_edit.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.last_target_line_edit.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.number_of_runs_line_edit.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.number_of_inspection_images_line_edit.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Last target", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Wait time", None))
        self.first_target_line_edit.setInputMask("")
        self.first_target_line_edit.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Testing", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Import  files", None))
        self.file_input_1_button.setText(QCoreApplication.translate("MainWindow", u"Import variable pitch location file", None))
        self.file_input_2_button.setText(QCoreApplication.translate("MainWindow", u"Import expantion location file", None))
        self.file_input_3_button.setText(QCoreApplication.translate("MainWindow", u"Input laser row data file", None))
        self.file_input_4_button.setText(QCoreApplication.translate("MainWindow", u"Log file during 1D error map x axis", None))
        self.run_action_button.setText(QCoreApplication.translate("MainWindow", u"Run action", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Select action", None))
        self.select_action_combo_box.setItemText(0, "")
        self.select_action_combo_box.setItemText(1, QCoreApplication.translate("MainWindow", u"Self centering repeatability plot", None))
        self.select_action_combo_box.setItemText(2, QCoreApplication.translate("MainWindow", u"Create glass scale certificate", None))
        self.select_action_combo_box.setItemText(3, QCoreApplication.translate("MainWindow", u"Calculate error map values-Vision", None))
        self.select_action_combo_box.setItemText(4, QCoreApplication.translate("MainWindow", u"Plot repetabilety graph vision", None))
        self.select_action_combo_box.setItemText(5, QCoreApplication.translate("MainWindow", u"Generate 1D error map buffer-Laser", None))
        self.select_action_combo_box.setItemText(6, QCoreApplication.translate("MainWindow", u"Plot thermal expantion-Vision", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Error mapping", None))
        self.info_text_edit.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuOpen.setTitle(QCoreApplication.translate("MainWindow", u"Open", None))
        self.menuSave.setTitle(QCoreApplication.translate("MainWindow", u"Save", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.cam_dock_widget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Camera feedback", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.cam_input_lable.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Camera type</p></body></html>", None))
        self.cam_type_combo_box.setItemText(0, "")
        self.cam_type_combo_box.setItemText(1, QCoreApplication.translate("MainWindow", u"BFS", None))
        self.cam_type_combo_box.setItemText(2, QCoreApplication.translate("MainWindow", u"Dahua_A550", None))
        self.cam_type_combo_box.setItemText(3, QCoreApplication.translate("MainWindow", u"Web_cam", None))

        self.select_circle_radio_button.setText(QCoreApplication.translate("MainWindow", u"Reference \n"
"Circle", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Camera index</p></body></html>", None))
        self.cam_id_combo_box.setItemText(0, "")
        self.cam_id_combo_box.setItemText(1, QCoreApplication.translate("MainWindow", u"0", None))
        self.cam_id_combo_box.setItemText(2, QCoreApplication.translate("MainWindow", u"1", None))
        self.cam_id_combo_box.setItemText(3, QCoreApplication.translate("MainWindow", u"2", None))

        self.start_camera_push_button.setText(QCoreApplication.translate("MainWindow", u"Start camera", None))
        self.stop_camera_push_button.setText(QCoreApplication.translate("MainWindow", u"Stop camera", None))
        self.save_image_push_button.setText(QCoreApplication.translate("MainWindow", u"Save image", None))
    # retranslateUi

